CREATE TABLE cheat_tester_sessions (
    session_id BINARY(16) NOT NULL,
    server_id VARCHAR(64) NOT NULL,
    staff_id BINARY(16) NOT NULL,
    target_id BINARY(16) NOT NULL,
    active_target_uuid CHAR(36) NULL,
    tester_type VARCHAR(32) NOT NULL,
    snapshot_text LONGTEXT NOT NULL,
    configuration_text MEDIUMTEXT NOT NULL,
    evidence_text MEDIUMTEXT NULL,
    state VARCHAR(24) NOT NULL,
    completion_reason VARCHAR(255) NULL,
    started_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    completed_at TIMESTAMP(6) NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    revision BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (session_id),
    UNIQUE KEY uq_cheat_tester_active_target (active_target_uuid),
    KEY idx_cheat_tester_recovery (server_id, state, expires_at),
    KEY idx_cheat_tester_staff (staff_id, state, started_at),
    CONSTRAINT chk_cheat_tester_state CHECK (state IN ('ACTIVE', 'RESTORED', 'CANCELLED', 'FAILED')),
    CONSTRAINT chk_cheat_tester_times CHECK (expires_at > started_at)
);
