---
exclude_paths:
  - "src/main/resources/migrations/**"
  - "src/main/resources/website-sync-migrations/**"

engines:
  lizard:
    exclude_paths:
      - "src/test/**"
  tsqllint:
    enabled: false
