package net.enthusia.staff.domain.auth;

public enum DiscordAuthorizationDenial {
    NONE,
    UNAUTHORIZED_OPERATION,
    UNAUTHORIZED_CONSEQUENCE,
    HELPER_CROSS_PLATFORM_FORBIDDEN,
    MINECRAFT_AUTHORIZATION_DENIED,
    PERMANENT_ACTION_REQUIRES_ADMIN,
    DURATION_EXCEEDS_LIMIT,
    CUSTOM_DURATION_NOT_PERMITTED,
    CUSTOM_CONSEQUENCE_REQUIRES_ADMIN,
    SELF_TARGET,
    TARGET_STAFF_PROTECTED,
    STALE_AUTHORIZATION
}
