package net.enthusia.staff.domain.auth;

public enum ModerationAction {
    ISSUE_POLICY_SANCTION,
    LOWER_RECOMMENDATION,
    RAISE_RECOMMENDATION,
    USE_CUSTOM_DURATION,
    USE_CUSTOM_COMBINATION,
    END_SANCTION,
    REVOKE_SANCTION,
    FULL_OVERTURN,
    REQUEST_FULL_OVERTURN,
    APPROVE_OVERTURN,
    RESTORE_ASSETS,
    OWNER_RECOVERY
}
