package net.enthusia.staff.domain.auth;

public enum ModerationAction {
    ISSUE_POLICY_SANCTION,
    REQUEST_POLICY_SANCTION,
    APPROVE_POLICY_SANCTION,
    LOWER_RECOMMENDATION,
    RAISE_RECOMMENDATION,
    USE_CUSTOM_DURATION,
    USE_CUSTOM_COMBINATION,
    END_SANCTION,
    REVOKE_SANCTION,
    FULL_OVERTURN,
    REQUEST_FULL_OVERTURN,
    APPROVE_OVERTURN,
    ACCEPT_APPEAL,
    APPLY_CASE_CONFISCATION,
    MODIFY_MARKET_RESTRICTION,
    MODIFY_REPUTATION_RESTRICTION,
    RESTORE_ASSETS,
    MANAGE_ACCOUNT_LINKS,
    OWNER_RECOVERY
}
