name: EnthusiaCurrency
main: com.enthusia.enthusiacurrency.EnthusiaCurrencyPlugin
version: 1.4.4
api-version: '1.21'
author: Enthusia
depend: [Vault]
softdepend: [PlaceholderAPI, Plan]

commands:
  balance:
    aliases: [bal, money]
    description: Shows your token balance.
    usage: /balance [player]
  deposit:
    description: Deposits currency items into your bank.
    usage: /deposit [amount|all]
  withdraw:
    description: Withdraws currency into physical items.
    usage: /withdraw <amount>
  pay:
    description: Pays another player.
    usage: /pay <player> <amount>
  baltop:
    description: Shows the top balances.
    usage: /baltop [page]
  currency:
    aliases: [ecurr]
    description: EnthusiaCurrency admin command.
    usage: /currency reload

permissions:
  currency.admin:
    default: op
  currency.balance.others:
    default: op
