package net.enthusia.staff.domain.sanction;

public enum SanctionType {
    WARNING,
    KICK,
    MUTE,
    BAN,
    NETWORK_BAN,
    NETWORK_IDENTITY_BAN,
    REPORT_RESTRICTION,
    REPUTATION_BLACKLIST,
    MARKET_BLACKLIST,
    INVENTORY_CONFISCATION,
    ENDER_CHEST_CONFISCATION,
    ECONOMY_CONFISCATION,
    CONTENT_REMOVAL,
    STALL_OWNERSHIP_REMOVAL
}
